name: CI

env:
  TARGET_FILE: 'config.yaml'
  YAML_PROPERTY_PATH: ''

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup gitops repo access
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}  

      - name: Checkout CD repo
        uses: actions/checkout@v4   
        with:
          ssh-key: ${{ secrets.MANIFEST_REPO_DEPLOY_KEY }}
          repository: ${{ secrets.MANIFEST_REPO }}
          
      - name: 'Configure git'
      # From https://github.com/orgs/community/discussions/26560#discussioncomment-3531273
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Update version
        run: |
          yq -i '${{ env.YAML_PROPERTY_PATH }} = ${{ github.run_number }} ' ${{ env.TARGET_FILE }}
    
      - name: Commit and push update
        run: |
          git commit -am "Update version in config"
          git push origin